### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by durrantmm** [heartsh/consalifold#1]
I can't get this work, I have very little experience with Rust, is there any way you could share a docker image?

**Comment by heartsh** [comment]
Thank you for your reporting.
Which is your situation?
- You cannot create a container using my Dockerfile (https://github.com/heartsh/consprob/blob/master/Dockerfile). (My Dockerfile instruction is in https://github.com/heartsh/consprob/blob/master/README.md or https://github.com/heartsh/consalifold/blob/master/README.md.)
- You cannot install ConsAlifold using Rust.

I can upload ConsAlifold's image, but I recommend building from Dockerfile due to the size of this image.

**Comment by durrantmm** [comment]
Great, I tried your dockerfile and it worked well, thank you.
